<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\name_prepopulate\NamePrepopulateHelper;

/**
 * Implements hook_entity_prepare_form().
 */
function name_prepopulate_entity_prepare_form(\Drupal\Core\Entity\EntityInterface $entity, $operation, \Drupal\Core\Form\FormStateInterface $form_state) {
  $nameField = 'field_name';

  $types = ['contact_message'];

  if (!in_array($entity->getEntityTypeId(), $types) || !($entity instanceof \Drupal\Core\Entity\FieldableEntityInterface)) {
    return;
  }

  if (!$entity->hasField($nameField) || $entity->get($nameField)->isEmpty()) {
    return;
  }

  $helper = new NamePrepopulateHelper($entity, $nameField);

  $helper->prepopulateFromAccount();
}

/**
 * Implements hook_entity_presave().
 */
function name_prepopulate_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  $nameField = 'field_name';

  $types = ['contact_message'];

  if (!in_array($entity->getEntityTypeId(), $types) || !($entity instanceof \Drupal\Core\Entity\FieldableEntityInterface)) {
    return;
  }

  $helper = new NamePrepopulateHelper($entity, $nameField);

  $helper->fillTextField($entity, 'name');
}
